services:
  api-dev:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - qdrant
    # profiles: ["dev"]
    networks:
      - app-network
    volumes:
      - ./storage:/app/storage
  
  qdrant:
    image: qdrant/qdrant:v1.15.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ~/qdrant_storage:/qdrant/storage:z
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api-dev
    networks:
      - app-network
    # profiles: ["dev"]

networks:
  app-network:
    driver: bridge
